class RojobaCo.Constants
    @DATE_STRING_FORMAT: 'YYYY-MM-DD'
    @DATE_STRING_DISPLAY_FORMAT: 'DD MMMM YYYY'
    @DATETIME_STRING_FORMAT: 'DD MMMM YYYY HH:mm'
    @BWA_DB: 'bwa_db'
    @SCHEDULED_JOB_STORE: 'ScheduledJob'
    @API_KEY = 'J8jKv6srQQ0R0Q4DH03see44h1lED1Ec'
    @API_URI = 'http://localhost:58950/'
    #@API_URI = 'https://bcapiprod.alu.bwg.co.za/'
    #@API_URI = 'https://bcapi.alu.bwg.co.za/'
